modLoader = "javafml" #mandatory
loaderVersion = "[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT License"
issueTrackerURL="https://github.com/Exploding-Creeper/SimpleSplashScreen/issues" #optional

[[mods]] #mandatory
modId = "simplesplashscreen" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Simple Splash Screen" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-splash-screen" #optional
logoFile="logo_light.png" #optional
credits="Thanks to Motschen who made the original Fabric version of this mod" #optional
authors="HypherionSA" #optional
description = '''
A mod that allows you to customize the Minecraft Loading Screen to your liking
'''

[[dependencies.simplesplashscreen]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[37,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.simplesplashscreen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,1.18)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.simplesplashscreen]]
modId = "cloth_config"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"
