modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId = "simplesplashscreen" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Simple Splash Screen" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="CustomSplashScreen.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
#authors="Love, Cheese and small house plants" #optional
description = '''

'''


[[dependencies.simplesplashscreen]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"


[[dependencies.simplesplashscreen]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
